language: elixir
elixir: '1.5'
otp_release: '20.1'
env:
  - MIX_ENV=test
before_install:
  - pip install --user cpp-coveralls
  - mix local.hex --force
  - mix local.rebar --force
install: 
  - mix deps.get
script:
  - mix coveralls.travis
after_success:
  - llvm-cov gcov priv/*.o
  - coveralls -n
