language: elixir
elixir: '1.5'
otp_release: '20.1'

before_install:
  - pip install --user cpp-coveralls
install: 
  - mix deps.get
script:
  - mix test
after_success:
  - llvm-cov gcov priv/*.o
  - coveralls -n --verbose
