language: elixir
elixir: '1.5'
otp_release: '20.1'
env:
  - MIX_ENV=test
before_install:
  - mix local.hex --force
  - mix local.rebar --force
install: 
  - mix deps.get
  - mix deps.compile
script:
  - mix coveralls.json
after_success:
  - llvm-cov gcov priv/*.o
  - bash <(curl -s https://codecov.io/bash) -X gcov
